### ISSUE TITLE
Can not use it in expo project

### ISSUE THREAD

**Issue by moonrailgun** [awslabs/clickstream-react-native#13]
### Describe the bug

![image](https://github.com/awslabs/clickstream-react-native/assets/6964737/f962b7c9-ac70-4fcf-ae38-7abff058e09a)

![image](https://github.com/awslabs/clickstream-react-native/assets/6964737/2cf2d48d-d992-4c5b-9060-e0b26caa9506)

when i try to install it and build it in xcode, its will throw those problem

### Steps To Reproduce

```typescript
Steps to reproduce the behavior:
1. create a expo project
2. install it with `expo install @aws/clickstream-react-native`
3. run `pod install` in `ios` folder.
4. throw this error
```

### Expected behavior

build pass 

### ClickstreamAnalytic React Native SDK Version

0.2.1(latest)

### React Native version

0.73.1

### The platform of the bug

iOS

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


</details>
```

### Is this a regression?

Yes

**Comment by zhu-xiaowei** [comment]
Hi, the Clickstream React Native SDK does not currently support direct installation in Expo projects. You can try running `npx expo prebuild` to convert your project into a standard React Native project with native modules, and then follow the SDK documentation for integration.

For the error you encountered, you can refer to this [issue](https://stackoverflow.com/questions/41663002/react-rctbridgemodule-h-file-not-found) and try unchecking the "Parallelize Build" option to see if it resolves the problem.

**Comment by moonrailgun** [comment]
i am try to install it in a exist react native project. install clickstream before and install expo later.
and much conflict.
android is work perfect but ios spent me over 4 days and no way to resolve.(cry).

already try use native spm link and react native link.

now i ignore expo module in ios platform and try to find other way to replace clickstream. but if i can resolve this problem, i will grad to continue use clickstream as our team backend data platform

**Comment by zhu-xiaowei** [comment]
Hi~ moonrailgun, thanks for your comments. We have a sample react-native app with Clickstream react native SDK integrated, you can refer to this [repo](https://github.com/aws-samples/clickstream-sdk-samples/tree/main/react-native) for details. In addition, can you provide a minimal sample project that only integrates the Clickstream react native SDK and provide the build steps to reproduce the issue, then you can contact us more conveniently via email xiaoweii@amazon.com.

**Comment by zhu-xiaowei** [comment]
This issue has been without any new replies or information for over 2 weeks. Feel free to contact us to provide more information, and I will go ahead and close this issue.
